name: ${project.name}
main: angga7togk.luckycrates.LuckyCrates
version: ${project.version}
api: 1.0.0
authors:
  - Angga7Togk
  - AraaCuteUwU

permissions:
  luckycrates:
    default: op
    children:
      luckycrates.command: true
      luckycrates.command.setcrate: true
      luckycrates.command.key: true
      luckycrates.command.keyall: true
      break.crates: true