name: ${project.name}
main: angga7togk.luckycrates.LuckyCrates
version: ${project.version}
api: 1.0.0
author: Angga7Togk

permissions:
  crates.command:
    default: op
  break.crates:
    default: op